// <auto-generated />
namespace CodeFirstEF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlertOutDoorMemberID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlertOutDoorMemberID));
        
        string IMigrationMetadata.Id
        {
            get { return "201303080922186_AlertOutDoorMemberID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
