// <auto-generated />
namespace CodeFirstEF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class WrokItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WrokItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201302050726498_WrokItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
