// <auto-generated />
namespace CodeFirstEF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMember_Profile_Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMember_Profile_Field));
        
        string IMigrationMetadata.Id
        {
            get { return "201303011531514_AddMember_Profile_Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
