//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Area
    {
        public Area()
        {
            this.Member_Profile = new HashSet<Member_Profile>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Key]
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string PCityCode { get; set; }

        public virtual ICollection<Member_Profile> Member_Profile { get; set; }
    }
}
