//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Group
    {
        public Group()
        {
            this.Member = new HashSet<Member>();
            this.Roles = new HashSet<Roles>();
        }
        [Key]
        public int GroupID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Member> Member { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
