//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Member
    {
        public Member()
        {
            this.Member_Action = new HashSet<Member_Action>();
        }
        [Key]
        public int MemberID { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public int GroupID { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public string LastIP { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddIP { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Member_Action> Member_Action { get; set; }
        public virtual Member_Profile Member_Profile { get; set; }
    }
}
