//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public abstract class Category
    {
        public Category()
        {
            this.PCateCode = string.Empty;

        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }


        [Key]
        [Required(ErrorMessage = "请输入类别代码.")]
        [Display(Name = "类别代码")]
        [MaxLength(20)]
        public string CateCode { get; set; }

        [Required(ErrorMessage = "请输入类别名称.")]
        [Display(Name = "类别名称")]
        [MaxLength(50)]
        public string CateName { get; set; }


        [Display(Name = "代码长度")]
        public int Length { get; set; }


        [Display(Name = "父级类别代码")]
        [MaxLength(20)]
        public string PCateCode { get; set; }

        [Display(Name = "排列序号")]
        public int OrderIndex { get; set; }

        [ScriptIgnore]
        public virtual Category PCategory { get; set; }

        [ScriptIgnore]
        public virtual ICollection<Category> ChildCategoies { get; set; }


    }
}
