// <auto-generated />
namespace UserProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlterGrouName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterGrouName));
        
        string IMigrationMetadata.Id
        {
            get { return "201301300851111_AlterGrouName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
